### ISSUE TITLE
Suggest delete melpa package or synchronize with org contrib‘s version

### ISSUE THREAD

**Issue by tumashu** [larstvei/ox-gfm#5]
melpa package: ox-gfm make users confuse, suggest delete or sync with org contrib's version

**Comment by larstvei** [comment]
This is a melpa issue, seeing that the maintainers of melpa controls what should be in melpa or not (note that I did not submit this to melpa, someone else did).

I'll make no effort to get it removed from melpa, because I'm not convinced that most users actually find it confusing. I would think that some users find it convenient that they are able to download this from melpa, instead of having to dig it out of the org/contribute.

**Comment by tumashu** [comment]
the.problem is that two version seem different, this.version can deal will index properly

**Comment by tumashu** [comment]
sorry, can not deal with index properly
